### ISSUE TITLE
[BUG] 自行构建版本运行错误

### ISSUE THREAD

**Issue by LovelyCane** [EggLinks/DanhengServer-Public#19]
错误描述：
自行构建版本运行错误
但是从项目Release页面下载的版本并没有任何在玩家进游戏前的错误（游戏内暂时未测试）

复现方法：
运行 从本地或使用Actions 进行构建的exe

错误内容：
以下为Actions构建出的exe

1、无法找到证书文件

[22:21:20] [Program] [INFO] Starting DanhengServer...
[22:21:20] [Program] [INFO] Loading Config File...
[22:21:20] [Program] [INFO] Loading Language...
[22:21:20] [I18nManager] [INFO] Loaded Language.
[22:21:20] [Database] [INFO] Loading Database...
[22:21:20] [Program] [INFO] Loaded Database Account.
[22:21:20] [Program] [WARN] You cannot enter the game yet. Please wait for all items to load before trying again
Application startup exception: System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, String fileName, String password)
   at EggLink.DanhengServer.WebServer.WebProgram.<>c.<BuildWebHost>b__1_2(ListenOptions listenOptions) in D:\a\DanhengServer-Public\DanhengServer-Public\WebServer\WebProgram.cs:line 26
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
   at EggLink.DanhengServer.WebServer.WebProgram.<>c__DisplayClass1_0.<BuildWebHost>b__1(KestrelServerOptions options) in D:\a\DanhengServer-Public\DanhengServer-Public\WebServer\WebProgram.cs:line 24
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, IHttpsConfigurationService httpsConfigurationService, ILoggerFactory loggerFactory, KestrelMetrics metrics)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.Security.Cryptography.CryptographicException: The system cannot find the file specified.
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, String fileName, String password)
   at EggLink.DanhengServer.WebServer.WebProgram.<>c.<BuildWebHost>b__1_2(ListenOptions listenOptions) in D:\a\DanhengServer-Public\DanhengServer-Public\WebServer\WebProgram.cs:line 26
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
   at EggLink.DanhengServer.WebServer.WebProgram.<>c__DisplayClass1_0.<BuildWebHost>b__1(KestrelServerOptions options) in D:\a\DanhengServer-Public\DanhengServer-Public\WebServer\WebProgram.cs:line 24
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource, KestrelMetrics metrics)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, IHttpsConfigurationService httpsConfigurationService, ILoggerFactory loggerFactory, KestrelMetrics metrics)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at EggLink.DanhengServer.WebServer.WebProgram.Main(String[] args, Int32 port, String address) in D:\a\DanhengServer-Public\DanhengServer-Public\WebServer\WebProgram.cs:line 11
   at EggLink.DanhengServer.Program.Program.EntryPoint.Main(String[] args) in D:\a\DanhengServer-Public\DanhengServer-Public\Program\Program\EntryPoint.cs:line 115
   at EggLink.DanhengServer.Program.Program.EntryPoint.<Main>(String[] args)

可以通过复制 certificate.p12 到运行目录解决

2、部分数据文件读取错误

[22:24:35] [ResourceManager] [ERROR] Failed to read FinishWay.json, file Error
[22:24:35] [ResourceManager] [ERROR] Error converting value "RogueMagicGetUnitCnt" to type
'EggLink.DanhengServer.Enums.Mission.MissionFinishTypeEnum'. Path 'FinishType', line 3, position 38.
[22:24:35] [ResourceManager] [ERROR]    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader,
Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader,
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean
checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)
   at EggLink.DanhengServer.Data.ResourceManager.LoadSingleExcelResource(Type cls) in
D:\a\DanhengServer-Public\DanhengServer-Public\Common\Data\ResourceManager.cs:line 98
[22:24:35] [ResourceManager] [INFO] Loaded 667 FinishWayExcel(s).
[22:24:35] [ResourceManager] [ERROR] Failed to read FuncUnlockData.json, file Error
[22:24:35] [ResourceManager] [ERROR] Error converting value "SubMissionTaken" to type
'EggLink.DanhengServer.Enums.Quest.ConditionTypeEnum'. Path 'Conditions[1].Type', line 9, position 31.
[22:24:35] [ResourceManager] [ERROR]    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader,
Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader,
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader,
JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader,
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType,
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean
checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type)
   at EggLink.DanhengServer.Data.ResourceManager.LoadSingleExcelResource(Type cls) in
D:\a\DanhengServer-Public\DanhengServer-Public\Common\Data\ResourceManager.cs:line 98
......
[22:24:39] [ResourceManager] [ERROR] Failed to read RogueBuffGroup.json, file Error
[22:24:39] [ResourceManager] [ERROR] An item with the same key has already been added. Key: 0
[22:24:39] [ResourceManager] [ERROR]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value,
InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at EggLink.DanhengServer.Data.Excel.RogueBuffGroupExcel.Loaded() in
D:\a\DanhengServer-Public\DanhengServer-Public\Common\Data\Excel\RogueBuffGroupExcel.cs:line 24
   at EggLink.DanhengServer.Data.ResourceManager.LoadSingleExcelResource(Type cls) in
D:\a\DanhengServer-Public\DanhengServer-Public\Common\Data\ResourceManager.cs:line 102

使用从项目Release页面下载的版本解决

**Comment by StopWuyu** [comment]
提示，公仓内部暂时不再更新，我们寻找到一种可以阻止篡改左下反盗卖提示后才会重新开源，请等待，若遇见bug欢迎在此或Discord服务器频道进行反馈

**Comment by StopWuyu** [comment]
提示，若想进入私仓，请积极做出贡献（包含提出bug，~~提交pr~~），在评估可信度后会考虑邀请进入私仓
